import { supabase } from '../lib/supabaseClient'

// The real, non-guessable secret a Fusion Pass QR encodes. Generated by the database
// (passes.token defaults to a UUIDv4 with dashes stripped — 32 hex chars, 122 bits of
// randomness, unique-constrained), never derived from anything about the student.
//
// There's no direct `select` on `passes` anymore (schema-lock-pass-tokens.sql) — any account that
// could read tokens straight out of the table could mint working forged passes for anyone without
// ever scanning a code, which defeats the point of a random token in the first place. Reading one
// only ever happens through get_pass_token(), which the database itself restricts to Admin.

// Admin-only — enforced inside the database function itself (public.staff_users, checked against
// the caller's real JWT), not just by what this app's UI happens to show. Returns null if the
// caller isn't Admin, the student has no pass, or the RPC otherwise rejects the call.
export async function fetchPassToken(studentUuid: string): Promise<string | null> {
  const { data, error } = await supabase.rpc('get_pass_token', { p_student_id: studentUuid })
  if (error) return null
  return (data as string | null) ?? null
}
